/*// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqfpMoKSFwkpwd8rmf66Eq_ZAqO1FAGVo',
    appId: '1:765124783925:web:4fbcfe4da486f90c3c667c',
    messagingSenderId: '765124783925',
    projectId: 'notification-fc192',
    authDomain: 'notification-fc192.firebaseapp.com',
    storageBucket: 'notification-fc192.firebasestorage.app',
    measurementId: 'G-N0BCXZ8VQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAP-XfHSmmpateg-PIfhoHWyMbQwiImhM',
    appId: '1:765124783925:android:d643a8e8ab4120ce3c667c',
    messagingSenderId: '765124783925',
    projectId: 'notification-fc192',
    storageBucket: 'notification-fc192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZfNHnwKq7XJProxPi-u7yGMH9_m_xqxA',
    appId: '1:765124783925:ios:62f760539540be813c667c',
    messagingSenderId: '765124783925',
    projectId: 'notification-fc192',
    storageBucket: 'notification-fc192.firebasestorage.app',
    iosBundleId: 'com.example.clearanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZfNHnwKq7XJProxPi-u7yGMH9_m_xqxA',
    appId: '1:765124783925:ios:62f760539540be813c667c',
    messagingSenderId: '765124783925',
    projectId: 'notification-fc192',
    storageBucket: 'notification-fc192.firebasestorage.app',
    iosBundleId: 'com.example.clearanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqfpMoKSFwkpwd8rmf66Eq_ZAqO1FAGVo',
    appId: '1:765124783925:web:19c1e1753c3d886d3c667c',
    messagingSenderId: '765124783925',
    projectId: 'notification-fc192',
    authDomain: 'notification-fc192.firebaseapp.com',
    storageBucket: 'notification-fc192.firebasestorage.app',
    measurementId: 'G-93ZB8PR3X6',
  );
}
*/